#version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8084:80"  # Mapea el puerto 80 del contenedor al puerto 8080 de la máquina host
    volumes:
      - ./html:/usr/share/nginx/html  # Mapea la carpeta html del host al contenedor
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Configuración personalizada de Nginx
